easy_admin:
    design:
        menu:
            - label: 'User'
              icon: 'users'
              children:
                - { label: 'Candidat', icon: 'user', entity: 'UserCandidat' }
                - { label: 'Recruteur', icon: 'user', entity: 'UserRecruteur' }
    site_name: 'ADMIN <em style="font-size: 80%;">Dashboard</em>'
    entities:
        UserCandidat:
            class: UserBundle\Entity\UserCandidat
            list:
                fields: ['nom', 'username', 'email', 'enabled', { property: 'roles'}]
            form:
                fields:
                    - 'nom'
                    - 'username'
                    - 'email'
                    - {property: 'password', type: 'password'}
                    - 'enabled'
                    - property: 'roles'
                      label: 'Roles'
                      type: choice
                      type_options:
                          expanded: true
                          multiple: true
                          choices: {'Candidat': 'ROLE_CANDIDAT', 'Recruteur': 'ROLE_RECRUTEUR','Administrator': 'ROLE_ADMIN'}
            password_encoding: { algorithm: 'bcrypt', cost: 12 }



        UserRecruteur:
            class: UserBundle\Entity\UserRecruteur
            list:
                fields: ['name', 'username', 'email', 'enabled']
            form:
                fields:
                    - 'name'
                    - 'username'
                    - 'email'
                    - { property: 'Password', type: 'password', type_options: { required: true } }
                    - 'enabled'
                    - property: 'roles'
                      label: 'Roles'
                      type: choice
                      type_options:
                          expanded: true
                          multiple: true
                          choices: {'Candidat': 'ROLE_CANDIDAT', 'Recruteur': 'ROLE_RECRUTEUR','Administrator': 'ROLE_ADMIN'}

    list:
        max_results: 10
    show:
        max_results: 10

