easy_admin:
    design:
        menu:
            - label: 'User'
              icon: 'users'
              children:
                - { label: 'Tout User', icon: 'user', entity: 'User' }
                - { label: 'Candidat', icon: 'user', entity: 'UserCandidat' }
                - { label: 'Recruteur', icon: 'user', entity: 'UserRecruteur' }
    site_name: 'ADMIN <em style="font-size: 80%;">Dashboard</em>'
    entities:
        User:
            class: UserBundle\Entity\User
            list:
                fields: ['username', 'email', 'enabled', { property: 'roles'}]
            edit:
                fields:
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', label: 'Password', type: 'text', type_options: { required: false } }
                    - 'enabled'
                    - property: 'roles'
                      label: 'Roles'
                      type: choice
                      type_options:
                          expanded: true
                          multiple: true
                          choices: {'Candidat': 'ROLE_CANDIDAT', 'Recruteur': 'ROLE_RECRUTEUR','Administrator': 'ROLE_ADMIN'}

            new:
                fields:
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', label: 'Password', type: 'text', type_options: { required: false } }
                    - 'enabled'
                    - property: 'roles'
                      label: 'Roles'
                      type: choice
                      type_options:
                          expanded: true
                          multiple: true
                          choices: {'Candidat': 'ROLE_CANDIDAT', 'Recruteur': 'ROLE_RECRUTEUR','Administrator': 'ROLE_ADMIN'}
                form_options: { validation_groups: ['Registration'] }

        UserCandidat:
            class: UserBundle\Entity\UserCandidat
            list:
                fields: ['username', 'email', 'enabled', { property: 'roles'}]
            edit:
                fields:
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', label: 'Password', type: 'text', type_options: { required: false } }
                    - 'enabled'
                    - property: 'roles'
                      label: 'Roles'
                      type: choice
                      type_options:
                          expanded: true
                          multiple: true
                          choices: {'Candidat': 'ROLE_CANDIDAT', 'Recruteur': 'ROLE_RECRUTEUR'}
                form_options: { validation_groups: ['Profile'] }

            new:
                fields:
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', label: 'Password', type: 'text', type_options: { required: false } }
                    - 'enabled'
                    - property: 'roles'
                      label: 'Roles'
                      type: choice
                      type_options:
                          expanded: true
                          multiple: true
                          choices: {'Candidat': 'ROLE_CANDIDAT', 'Recruteur': 'ROLE_RECRUTEUR'}
                form_options: { validation_groups: ['Registration'] }

        UserRecruteur:
            class: UserBundle\Entity\UserRecruteur
            list:
                fields: ['username', 'email', 'enabled', { property: 'roles'}]
            edit:
                fields:
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', label: 'Password', type: 'text', type_options: { required: false } }
                    - 'enabled'
                    - property: 'roles'
                      label: 'Roles'
                      type: choice
                      type_options:
                          expanded: true
                          multiple: true
                          choices: {'Candidat': 'ROLE_CANDIDAT', 'Recruteur': 'ROLE_RECRUTEUR','Administrator': 'ROLE_ADMIN'}
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', label: 'Password', type: 'text', type_options: { required: true } }
                    - 'enabled'
                    - property: 'roles'
                      label: 'Roles'
                      type: choice
                      type_options:
                          expanded: true
                          multiple: true
                          choices: {'Candidat': 'ROLE_CANDIDAT', 'Recruteur': 'ROLE_RECRUTEUR'}
                form_options: { validation_groups: ['Registration'] }

    list:
        max_results: 10
    show:
        max_results: 10

