app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation

user_cadidat_registration:
    path:  /candidat/register
    defaults: { _controller: UserBundle:RegistrationUser:registerCandidat }

user_recruteur_registration:
    path:  /recruteur/register
    defaults: { _controller: UserBundle:RegistrationUser:registerRecruteur }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
