<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function findByQuiz($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT question.reponce
                FROM UserBundle:Question question
                WHERE question.quiz = :id'
            )
            ->setParameter('id', $id)
            ->getResult();

    }
}
